#!/usr/bin/env python


import os, sys, platform, urllib

#Check if argument is specified
if len(sys.argv)>1:
	requested_vers=(sys.argv[1])
else:
	print ("Please write Firefox version")
	sys.exit()



#Get requested firefox version
def get_firefox():
        url="https://ftp.mozilla.org/pub/firefox/releases/{version}/linux-{proc}/en-US/firefox-{version}.tar.bz2".format(version=requested_vers, proc=platform.processor())
        file="firefox-{version}.tar.bz2".format(version=requested_vers)
        if urllib.urlopen(url).getcode()>=400:
                print "Couldn't fetch this Firefox's version"
		os._exit(1)

	print "***Check if version is local***"
	if not os.path.isdir("/opt/firefox/{version}".format(version=requested_vers)):
		os.system("sudo mkdir -p /opt/firefox/{version}".format(version=requested_vers))
		print "***Downloading Firefox***"
		urllib.urlretrieve(url, filename=file)
		os.system("sudo tar xjf {file} -C /opt/firefox/{version}".format(file=file, version=requested_vers))
		os.system("sudo ln -s -f /opt/firefox/{version}/firefox/firefox /usr/bin/firefox".format(version=requested_vers))
		print "Firefox {version} has been activated.".format(version=requested_vers)
		os.remove(file)
	else:
		print "Firefox {version} present locally. Activating it.".format(version=requested_vers)
		os.system("sudo ln -s -f /opt/firefox/{version}/firefox/firefox /usr/bin/firefox".format(version=requested_vers))
		print "Firefox {version} has been activated.".format(version=requested_vers)

#Compare current version with the requested one
def compare (requested_vers):
	cmd = os.popen('firefox --version').read()
	c = cmd.split(" ")
	if str(c[2]).strip() == str(requested_vers):
		print "***Already run with requested version***"
#		sys.exit()
	else:
		get_firefox()

try:compare (requested_vers)
except:get_firefox()

os.system('grep -q CURRENT_FIREFOX_VERSION /etc/environment || echo "CURRENT_FIREFOX_VERSION="suncdcd"" |sudo tee -a /etc/environment')
os.system("sudo sed -i 's/CURRENT_FIREFOX_VERSION.*/CURRENT_FIREFOX_VERSION=\"{version}\"/' /etc/environment".format(version=requested_vers))
#os.system('bash -c export CURRENT_FIREFOX_VERSION="{version}"'.format(version=requested_vers))

#execfile('/etc/environment')
